# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d002e82f538c325e221d4266a8d52203e46bd5c2ff20e332406d8b439ee575e41e1e3cded6df5276d14d7e87fcadce2be5b8a3ce2d9d8fd5d4d40579f78b5696

test:
  secret_key_base: 912b250bac108f79e0e7fce1b35c0f624ecbda313adc4d1a2482c13de61047ce4635822dc982024385af5a98d69bdf527450c99695606950f98f4a214f43c7c2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
